import { PlayCard } from "../types/playCard";

export const charDeck: PlayCard[] = [
    {
        id: 1,
        lvl: 0,
        exp: 0,
        exp_points: 0,
        name: "Jack",
        profession: "Investor",
        description: "5 years ago collected airdrops, and now he invests in blockchain startups and makes good money.",
        image: "investor",
        key_power: 'balance',
        balance_hp: 150,
        energy_mp: 100,
        stats: {
            balance: 15,
            mind: 10,
            energy: 10,
        },
        skills: [
            {
                name: "Kick",
                id: 1,
                description: "Just kick (default)",
                cost: 0,
                target: 'enemy',
                multiplier: 1,
                bp: [25, 2],
                amount: 0,
            },
            {
                name: "Refuse",
                id: 2,
                description: "Refuse to finance",
                cost: 20,
                target: 'enemy',
                multiplier: 1.2,
                bp: [104, 25],
                amount: 0,
            },
            {
                name: "Profitable",
                id: 3,
                description: "Profitable investment in project",
                cost: 30,
                target: 'enemy',
                multiplier: 1.3,
                bp: [0, 0],
                amount: 0,
            },
            {
                name: "Buy",
                id: 4,
                description: "Buy a project",
                //image: "buyProject",
                cost: 40,
                target: 'enemy',
                multiplier: 1.6,
                bp: [78, 25],
                amount: 0,
            }

        ],
        items: [
            {
                id: 1001,
                name: "Balance Potion(HP)",
                description: "Balance Potion",
                color: "rgb(204, 153, 0)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1002,
                name: "Energy Potion(MP)",
                description: "Energy Potion",
                color: "rgb(22 163 74)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1003,
                name: "Experience  Potion",
                description: "Exp Potion",
                color: "silver",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1004,
                name: "Bal+Enrg",
                description: "Bal+Enrg Potion",
                color: "gray",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            }
        ],
        inventory: [],
    },
    {
        id: 2,
        lvl: 0,
        exp: 0,
        exp_points: 0,
        name: "Rick",
        profession: "Developer",
        description: "is a smart descendant of virgin lands, a true hard worker. Makes web3 systems for users.",
        image: "developer",
        key_power: 'mind',
        balance_hp: 100,
        energy_mp: 100,
        stats: {
            balance: 10,
            mind: 15,
            energy: 10,
        },
        skills: [
            {
                name: "Kick",
                id: 1,
                description: "Just kick (default)",
                cost: 0,
                target: 'enemy',
                multiplier: 1,
                bp: [25, 2],
                amount: 0,
            },
            {
                name: "Refuse",
                id: 2,
                description: "Refuse to finance",
                cost: 20,
                target: 'enemy',
                multiplier: 1.2,
                bp: [104, 25],
                amount: 0,
            },
            {
                name: "Profitable",
                id: 3,
                description: "Profitable investment in project",
                cost: 30,
                target: 'enemy',
                multiplier: 1.3,
                bp: [0, 0],
                amount: 0,
            },
            {
                name: "Buy",
                id: 4,
                description: "Buy a project",
                cost: 40,
                target: 'enemy',
                multiplier: 1.6,
                bp: [78, 25],
                amount: 0,
            }
        ],
        inventory: [],
        items: [
            {
                id: 1001,
                name: "Balance Potion(HP)",
                description: "Balance Potion",
                color: "rgb(204, 153, 0)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1002,
                name: "Energy Potion(MP)",
                description: "Energy Potion",
                color: "rgb(22 163 74)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1003,
                name: "Experience  Potion",
                description: "Exp Potion",
                color: "silver",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1004,
                name: "Bal+Enrg",
                description: "Bal+Enrg Potion",
                color: "gray",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            }
        ],
    },
    {
        id: 3,
        lvl: 0,
        exp: 0,
        exp_points: 0,
        name: "Austin",
        profession: "Hamster",
        description: "participates in all free activities and airdrops. He is happy when he gets any free tokens. Trusting.",
        image: "hamster",
        key_power: 'energy',
        balance_hp: 100,
        energy_mp: 150,
        stats: {
            balance: 10,
            mind: 10,
            energy: 15,
        },
        skills: [
            {
                name: "Kick",
                id: 1,
                description: "Just kick (default)",
                cost: 0,
                target: 'enemy',
                multiplier: 1,
                bp: [25, 2],
                amount: 0,
            },
            {
                name: "Refuse",
                id: 2,
                description: "Refuse to finance",
                cost: 20,
                target: 'enemy',
                multiplier: 1.2,
                bp: [104, 25],
                amount: 0,
            },
            {
                name: "Profitable",
                id: 3,
                description: "Profitable investment in project",
                cost: 30,
                target: 'enemy',
                multiplier: 1.3,
                bp: [0, 0],
                amount: 0,
            },
            {
                name: "Buy",
                id: 4,
                description: "Buy a project",
                cost: 40,
                target: 'enemy',
                multiplier: 1.6,
                bp: [78, 25],
                amount: 0,
            }
        ],
        inventory: [],
        items: [
            {
                id: 1001,
                name: "Balance Potion(HP)",
                description: "Balance Potion",
                color: "rgb(204, 153, 0)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1002,
                name: "Energy Potion(MP)",
                description: "Energy Potion",
                color: "rgb(22 163 74)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1003,
                name: "Experience  Potion",
                description: "Exp Potion",
                color: "silver",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1004,
                name: "Bal+Enrg",
                description: "Bal+Enrg Potion",
                color: "gray",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            }
        ],
    },
    {
        id: 4,
        lvl: 0,
        exp: 0,
        exp_points: 0,
        name: "Larry",
        profession: "Influencer",
        description: "does reviews new blockchain projects and activities, loves his subscribers and publishes expensive advertising.",
        image: "influencer",
        key_power: 'balance',
        balance_hp: 150,
        energy_mp: 100,
        stats: {
            balance: 15,
            mind: 10,
            energy: 10,
        },
        skills: [
            {
                name: "Kick",
                id: 1,
                description: "Just kick (default)",
                cost: 0,
                target: 'enemy',
                multiplier: 1,
                bp: [25, 2],
                amount: 0,
            },
            {
                name: "Refuse",
                id: 2,
                description: "Refuse to finance",
                cost: 20,
                target: 'enemy',
                multiplier: 1.2,
                bp: [104, 25],
                amount: 0,
            },
            {
                name: "Profitable",
                id: 3,
                description: "Profitable investment in project",
                cost: 30,
                target: 'enemy',
                multiplier: 1.3,
                bp: [0, 0],
                amount: 0,
            },
            {
                name: "Buy",
                id: 4,
                description: "Buy a project",
                cost: 40,
                target: 'enemy',
                multiplier: 1.6,
                bp: [78, 25],
                amount: 0,
            }
        ],
        inventory: [],
        items: [
            {
                id: 1001,
                name: "Balance Potion(HP)",
                description: "Balance Potion",
                color: "rgb(204, 153, 0)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1002,
                name: "Energy Potion(MP)",
                description: "Energy Potion",
                color: "rgb(22 163 74)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1003,
                name: "Experience  Potion",
                description: "Exp Potion",
                color: "silver",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1004,
                name: "Bal+Enrg",
                description: "Bal+Enrg Potion",
                color: "gray",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            }
        ],
    },
    {
        id: 5,
        lvl: 0,
        exp: 0,
        exp_points: 0,
        name: "Anon",
        profession: "Scammer",
        description: "is constantly comes up with ways to scam and steal cryptocurrency from honest users. Afraid of deanonymization.",
        image: "scammer",
        key_power: 'mind',
        balance_hp: 100,
        energy_mp: 100,
        stats: {
            balance: 10,
            mind: 15,
            energy: 10,
        },
        skills: [
            {
                name: "Kick",
                id: 1,
                description: "Just kick (default)",
                cost: 0,
                target: 'enemy',
                multiplier: 1,
                bp: [25, 2],
                amount: 0,
            },
            {
                name: "Refuse",
                id: 2,
                description: "Refuse to finance",
                cost: 20,
                target: 'enemy',
                multiplier: 1.2,
                bp: [104, 25],
                amount: 0,
            },
            {
                name: "Profitable",
                id: 3,
                description: "Profitable investment in project",
                cost: 30,
                target: 'enemy',
                multiplier: 1.3,
                bp: [0, 0],
                amount: 0,
            },
            {
                name: "Buy",
                id: 4,
                description: "Buy a project",
                cost: 40,
                target: 'enemy',
                multiplier: 1.6,
                bp: [78, 25],
                amount: 0,
            }
        ],
        inventory: [],
        items: [
            {
                id: 1001,
                name: "Balance Potion(HP)",
                description: "Balance Potion",
                color: "rgb(204, 153, 0)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1002,
                name: "Energy Potion(MP)",
                description: "Energy Potion",
                color: "rgb(22 163 74)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1003,
                name: "Experience  Potion",
                description: "Exp Potion",
                color: "silver",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1004,
                name: "Bal+Enrg",
                description: "Bal+Enrg Potion",
                color: "gray",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            }
        ],
    },
    {
        id: 6,
        lvl: 0,
        exp: 0,
        exp_points: 0,
        name: "Jimmy",
        profession: "Ludoman",
        description: "is a crazy fanatic of gambling web3 games, one day he will get very lucky and he will stop. But it is not true.",
        image: "ludoman",
        key_power: 'energy',
        balance_hp: 100,
        energy_mp: 150,
        stats: {
            balance: 10,
            mind: 10,
            energy: 15,
        },
        skills: [
            {
                name: "Kick",
                id: 1,
                description: "Just kick (default)",
                cost: 0,
                target: 'enemy',
                multiplier: 1,
                bp: [25, 2],
                amount: 0,
            },
            {
                name: "Refuse",
                id: 2,
                description: "Refuse to finance",
                cost: 20,
                target: 'enemy',
                multiplier: 1.2,
                bp: [104, 25],
                amount: 0,
            },
            {
                name: "Profitable",
                id: 3,
                description: "Profitable investment in project",
                cost: 30,
                target: 'enemy',
                multiplier: 1.3,
                bp: [0, 0],
                amount: 0,
            },
            {
                name: "Buy",
                id: 4,
                description: "Buy a project",
                cost: 40,
                target: 'enemy',
                multiplier: 1.6,
                bp: [78, 25],
                amount: 0,
            }
        ],
        inventory: [],
        items: [
            {
                id: 1001,
                name: "Balance Potion(HP)",
                description: "Balance Potion",
                color: "rgb(204, 153, 0)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1002,
                name: "Energy Potion(MP)",
                description: "Energy Potion",
                color: "rgb(22 163 74)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1003,
                name: "Experience  Potion",
                description: "Exp Potion",
                color: "silver",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1004,
                name: "Bal+Enrg",
                description: "Bal+Enrg Potion",
                color: "gray",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            }
        ],
    },
    {
        id: 7,
        lvl: 0,
        exp: 0,
        exp_points: 0,
        name: "Barry",
        profession: "Institutional",
        description: "publicly criticizes cryptocurrency and advocates for regulation, but secretly he keeps most of his money in bitcoin.",
        image: "institutional",
        key_power: 'balance',
        balance_hp: 150,
        energy_mp: 100,
        stats: {
            balance: 15,
            mind: 10,
            energy: 10,
        },
        skills: [
            {
                name: "Kick",
                id: 1,
                description: "Just kick (default)",
                cost: 0,
                target: 'enemy',
                multiplier: 1,
                bp: [25, 2],
                amount: 0,
            },
            {
                name: "Refuse",
                id: 2,
                description: "Refuse to finance",
                cost: 20,
                target: 'enemy',
                multiplier: 1.2,
                bp: [104, 25],
                amount: 0,
            },
            {
                name: "Profitable",
                id: 3,
                description: "Profitable investment in project",
                cost: 30,
                target: 'enemy',
                multiplier: 1.3,
                bp: [0, 0],
                amount: 0,
            },
            {
                name: "Buy",
                id: 4,
                description: "Buy a project",
                cost: 40,
                target: 'enemy',
                multiplier: 1.6,
                bp: [78, 25],
                amount: 0,
            }
        ],
        inventory: [],
        items: [
            {
                id: 1001,
                name: "Balance Potion(HP)",
                description: "Balance Potion",
                color: "rgb(204, 153, 0)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1002,
                name: "Energy Potion(MP)",
                description: "Energy Potion",
                color: "rgb(22 163 74)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1003,
                name: "Experience  Potion",
                description: "Exp Potion",
                color: "silver",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1004,
                name: "Bal+Enrg",
                description: "Bal+Enrg Potion",
                color: "gray",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            }
        ],
    },
    {
        id: 8,
        lvl: 0,
        exp: 0,
        exp_points: 0,
        name: "Alex",
        profession: "Founder",
        description: "comes up with ideas for projects and seeks funding, builds strategies and manages the team.",
        image: "founder",
        key_power: 'mind',
        balance_hp: 100,
        energy_mp: 100,
        stats: {
            balance: 10,
            mind: 15,
            energy: 10,
        },
        skills: [
            {
                name: "Kick",
                id: 1,
                description: "Just kick (default)",
                cost: 0,
                target: 'enemy',
                multiplier: 1,
                bp: [25, 2],
                amount: 0,
            },
            {
                name: "Refuse",
                id: 2,
                description: "Refuse to finance",
                cost: 20,
                target: 'enemy',
                multiplier: 1.2,
                bp: [104, 25],
                amount: 0,
            },
            {
                name: "Profitable",
                id: 3,
                description: "Profitable investment in project",
                cost: 30,
                target: 'enemy',
                multiplier: 1.3,
                bp: [0, 0],
                amount: 0,
            },
            {
                name: "Buy",
                id: 4,
                description: "Buy a project",
                cost: 40,
                target: 'enemy',
                multiplier: 1.6,
                bp: [78, 25],
                amount: 0,
            }
        ],
        inventory: [],
        items: [
            {
                id: 1001,
                name: "Balance Potion(HP)",
                description: "Balance Potion",
                color: "rgb(204, 153, 0)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1002,
                name: "Energy Potion(MP)",
                description: "Energy Potion",
                color: "rgb(22 163 74)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1003,
                name: "Experience  Potion",
                description: "Exp Potion",
                color: "silver",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1004,
                name: "Bal+Enrg",
                description: "Bal+Enrg Potion",
                color: "gray",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            }
        ],
    },
    {
        id: 9,
        lvl: 0,
        exp: 0,
        exp_points: 0,
        name: "Michael",
        profession: "NFTartist",
        description: "loves to draw and paint, participates in exhibitions and promotes his conceptual art in the form of NFT.",
        image: "NFTartist",
        key_power: 'energy',
        balance_hp: 100,
        energy_mp: 150,
        stats: {
            balance: 10,
            mind: 10,
            energy: 15,
        },
        skills: [
            {
                name: "Kick",
                id: 1,
                description: "Just kick (default)",
                cost: 0,
                target: 'enemy',
                multiplier: 1,
                bp: [25, 2],
                amount: 0,
            },
            {
                name: "Refuse",
                id: 2,
                description: "Refuse to finance",
                cost: 20,
                target: 'enemy',
                multiplier: 1.2,
                bp: [104, 25],
                amount: 0,
            },
            {
                name: "Profitable",
                id: 3,
                description: "Profitable investment in project",
                cost: 30,
                target: 'enemy',
                multiplier: 1.3,
                bp: [0, 0],
                amount: 0,
            },
            {
                name: "Buy",
                id: 4,
                description: "Buy a project",
                cost: 40,
                target: 'enemy',
                multiplier: 1.6,
                bp: [78, 25],
                amount: 0,
            }
        ],
        inventory: [],
        items: [
            {
                id: 1001,
                name: "Balance Potion(HP)",
                description: "Balance Potion",
                color: "rgb(204, 153, 0)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1002,
                name: "Energy Potion(MP)",
                description: "Energy Potion",
                color: "rgb(22 163 74)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1003,
                name: "Experience  Potion",
                description: "Exp Potion",
                color: "silver",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1004,
                name: "Bal+Enrg",
                description: "Bal+Enrg Potion",
                color: "gray",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            }
        ],
    },
    {
        id: 10,
        lvl: 0,
        exp: 0,
        exp_points: 0,
        name: "Alfred",
        profession: "Whale",
        description: "is the holder of a large number of assets in blockchains. Money for him is just a tool for managing the market and earning more.",
        image: "whale",
        key_power: 'balance',
        balance_hp: 150,
        energy_mp: 100,
        stats: {
            balance: 15,
            mind: 10,
            energy: 10,
        },
        skills: [
            {
                name: "Kick",
                id: 1,
                description: "Just kick (default)",
                cost: 0,
                target: 'enemy',
                multiplier: 1,
                bp: [25, 2],
                amount: 0,
            },
            {
                name: "Refuse",
                id: 2,
                description: "Refuse to finance",
                cost: 20,
                target: 'enemy',
                multiplier: 1.2,
                bp: [104, 25],
                amount: 0,
            },
            {
                name: "Profitable",
                id: 3,
                description: "Profitable investment in project",
                cost: 30,
                target: 'enemy',
                multiplier: 1.3,
                bp: [0, 0],
                amount: 0,
            },
            {
                name: "Buy",
                id: 4,
                description: "Buy a project",
                cost: 40,
                target: 'enemy',
                multiplier: 1.6,
                bp: [78, 25],
                amount: 0,
            }
        ],
        inventory: [],
        items: [
            {
                id: 1001,
                name: "Balance Potion(HP)",
                description: "Balance Potion",
                color: "rgb(204, 153, 0)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1002,
                name: "Energy Potion(MP)",
                description: "Energy Potion",
                color: "rgb(22 163 74)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1003,
                name: "Experience  Potion",
                description: "Exp Potion",
                color: "silver",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1004,
                name: "Bal+Enrg",
                description: "Bal+Enrg Potion",
                color: "gray",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            }
        ],
    },
    {
        id: 11,
        lvl: 0,
        exp: 0,
        exp_points: 0,
        name: "Jerry",
        profession: "Trader",
        description: "trades cryptocurrency and builds private trading strategies. Sometimes he himself is shocked by his ideas.",
        image: "trader",
        key_power: 'mind',
        balance_hp: 100,
        energy_mp: 100,
        stats: {
            balance: 10,
            mind: 15,
            energy: 10,
        },
        skills: [
            {
                name: "Kick",
                id: 1,
                description: "Just kick (default)",
                cost: 0,
                target: 'enemy',
                multiplier: 1,
                bp: [25, 2],
                amount: 0,
            },
            {
                name: "Refuse",
                id: 2,
                description: "Refuse to finance",
                cost: 20,
                target: 'enemy',
                multiplier: 1.2,
                bp: [104, 25],
                amount: 0,
            },
            {
                name: "Profitable",
                id: 3,
                description: "Profitable investment in project",
                cost: 30,
                target: 'enemy',
                multiplier: 1.3,
                bp: [0, 0],
                amount: 0,
            },
            {
                name: "Buy",
                id: 4,
                description: "Buy a project",
                cost: 40,
                target: 'enemy',
                multiplier: 1.6,
                bp: [78, 25],
                amount: 0,
            }
        ],
        inventory: [],
        items: [
            {
                id: 1001,
                name: "Balance Potion(HP)",
                description: "Balance Potion",
                color: "rgb(204, 153, 0)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1002,
                name: "Energy Potion(MP)",
                description: "Energy Potion",
                color: "rgb(22 163 74)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1003,
                name: "Experience  Potion",
                description: "Exp Potion",
                color: "silver",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1004,
                name: "Bal+Enrg",
                description: "Bal+Enrg Potion",
                color: "gray",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            }
        ],
    },
    {
        id: 12,
        lvl: 0,
        exp: 0,
        exp_points: 0,
        name: "Lilly",
        profession: "Support",
        description: "works in the user support service of various projects. She loves to communicate with cryptans and help them.",
        image: "support",
        key_power: 'energy',
        balance_hp: 100,
        energy_mp: 150,
        stats: {
            balance: 10,
            mind: 10,
            energy: 15,
        },
        skills: [
            {
                name: "Kick",
                id: 1,
                description: "Just kick (default)",
                cost: 0,
                target: 'enemy',
                multiplier: 1,
                bp: [25, 2],
                amount: 0,
            },
            {
                name: "Refuse",
                id: 2,
                description: "Refuse to finance",
                cost: 20,
                target: 'enemy',
                multiplier: 1.2,
                bp: [104, 25],
                amount: 0,
            },
            {
                name: "Profitable",
                id: 3,
                description: "Profitable investment in project",
                cost: 30,
                target: 'enemy',
                multiplier: 1.3,
                bp: [0, 0],
                amount: 0,
            },
            {
                name: "Buy",
                id: 4,
                description: "Buy a project",
                cost: 40,
                target: 'enemy',
                multiplier: 1.6,
                bp: [78, 25],
                amount: 0,
            }
        ],
        inventory: [],
        items: [
            {
                id: 1001,
                name: "Balance Potion(HP)",
                description: "Balance Potion",
                color: "rgb(204, 153, 0)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1002,
                name: "Energy Potion(MP)",
                description: "Energy Potion",
                color: "rgb(22 163 74)",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1003,
                name: "Experience  Potion",
                description: "Exp Potion",
                color: "silver",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            },
            {
                id: 1004,
                name: "Bal+Enrg",
                description: "Bal+Enrg Potion",
                color: "gray",
                amount: 0,
                cost: 0,
                multiplier: 1,
                target: 'self',
                bp: [0, 0]
            }
        ],
    },
];
